//Song
export const FETCH_SONG = "FETCH_SONG";
export const ON_PLAY = "ON_PLAY";
export const ON_PAUSE = "ON_PAUSE";
export const TOGGLE_PLAY = "TOGGLE_PLAY";
export const FETCH_SONG_SUCCESS = "FETCH_SONG_SUCCESS";
export const START_FETCHING_SONG = "START_FETCHING_SONG";
export const FETCH_SONG_FAILURE = "FETCH_SONG_FAILURE";

//Queue
export const TOGGLE_QUEUE = "TOGGLE_QUEUE";
export const ADD_SONG_TO_QUEUE = "ADD_SONG_TO_QUEUE";
export const CLEAR_QUEUE = 'CLEAR_QUEUE';
export const DELETE_QUEUE_ITEM = "DELETE_QUEUE_ITEM";

//UI
export const TOGGLE_DROPDOWN = "TOGGLE_DROPDOWN";
export const EFFECT_LAZYLOAD_IMAGE_PLAY = "EFFECT_LAZYLOAD_IMAGE_PLAY";
export const EFFECT_LAZYLOAD_IMAGE_PAUSE = "EFFECT_LAZYLOAD_IMAGE_PAUSE";
export const TOGGLE_MODAL = "TOGGLE_MODAL";

//chart
export const FETCH_POP_CHART = "FETCH_POP_CHART";
export const FETCH_KPOP_CHART = "FETCH_KPOP_CHART";
export const FETCH_VPOP_CHART = "FETCH_VPOP_CHART";
export const CHANGE_ACTIVE_CHART = "CHANGE_ACTIVE_CHART";

//authen
export const START_PROCESSING = "START_PROCESSING";
export const LOGIN_IN_SUCCESS = "LOGIN_IN_SUCCESS";
export const FINISH_PROCESSING = "FINISH_PROCESSING";
export const LOG_OUT = "LOG_OUT";

//playlist
export const CREATE_PLAYLIST = "CREATE_PLAYLIST";
export const DELETE_PLAYLIST = "DELETE_PLAYLIST";
export const ADD_SONG_TO_PLAYLIST = "ADD_SONG_TO_PLAYLIST";
export const GET_PLAYLIST_COLLECTION = "GET_PLAYLIST_COLLECTION";